server:
  port: 8080

spring:
  application:
    name: new-ab1-workflow
  threads:
    virtual:
      enabled: true

# 下游微服务独立配置属性
downstream:
  llm:
    base-url: http://180.96.8.44/wstock_share # 大模型服务，走主站公网测试网关
    max-connections: 300
    pending-acquire-max-count: 500
    connect-timeout: 2s
    response-timeout: 60s
  rag:
    base-url: http://180.96.8.44/wstock_share # RAG检索服务，直连主站公网中转
    max-connections: 100
    connect-timeout: 2s
    response-timeout: 10s
  dpu:
    base-url: http://180.96.8.44/wstock_share # DPU行情数据服务，直连主站公网中转
    max-connections: 100
    connect-timeout: 2s
    response-timeout: 10s
  ner:
    base-url: http://10.102.16.20 # NER实体识别服务，直连局域网实体微服务
    max-connections: 100
    connect-timeout: 2s
    response-timeout: 10s
  viewpoint:
    base-url: http://wx.wind.com.cn # 观点校验服务，直连局域网工作流引擎
    max-connections: 100
    connect-timeout: 2s
    response-timeout: 30s
  rewrite:
    base-url: http://10.10.178.25:12239 # 改写服务，直接调用局域网大模型兼容网关
    max-connections: 100
    connect-timeout: 2s
    response-timeout: 10s

# 业务特性配置
app:
  session:
    prod-session: "mock-prod-session-id"
  env: "test" # 当前运行环境，测试时可模拟本地
