CREATE TABLE IF NOT EXISTS agent_conversation (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    user_id VARCHAR(64) NOT NULL COMMENT '用户标识',
    session_id VARCHAR(128) NOT NULL COMMENT '多轮会话标识',
    status TINYINT UNSIGNED NOT NULL COMMENT '会话状态',
    context_status TINYINT UNSIGNED NOT NULL COMMENT '上下文治理状态',
    latest_turn_no INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已分配最大轮次号',
    latest_summary_id BIGINT UNSIGNED NULL COMMENT '最新有效摘要主键',
    latest_summary_version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最新摘要版本',
    context_version INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '上下文语义版本',
    lock_version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '通用乐观锁版本',
    execution_owner VARCHAR(128) NULL COMMENT '当前执行租约持有者',
    execution_epoch BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租约隔离栅栏版本',
    execution_expire_time DATETIME(3) NULL COMMENT '执行租约过期时间',
    provider_code VARCHAR(64) NULL COMMENT '当前模型供应方编码',
    route_id VARCHAR(64) NULL COMMENT '当前模型路由标识',
    api_protocol VARCHAR(32) NULL COMMENT '当前模型协议',
    model_name VARCHAR(128) NULL COMMENT '当前主模型名称',
    system_prompt_version VARCHAR(64) NULL COMMENT '系统提示词版本',
    system_prompt_hash CHAR(64) NULL COMMENT '系统提示词内容哈希',
    tool_definition_version VARCHAR(64) NULL COMMENT '工具定义版本',
    tool_schema_hash CHAR(64) NULL COMMENT '实际工具定义哈希',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_session (user_id(64), session_id(128)),
    KEY idx_status_update_time (status, update_time),
    KEY idx_execution_expire_time (execution_expire_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Agent 会话';

CREATE TABLE IF NOT EXISTS conversation_turn (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    conversation_id BIGINT UNSIGNED NOT NULL COMMENT '所属会话主键',
    turn_no INT UNSIGNED NOT NULL COMMENT '会话内轮次号',
    task_id VARCHAR(128) NOT NULL COMMENT '单次请求幂等标识',
    user_content MEDIUMTEXT NOT NULL COMMENT '用户显式输入',
    assistant_content MEDIUMTEXT NULL COMMENT '助手最终显式回答',
    status TINYINT UNSIGNED NOT NULL COMMENT '轮次状态',
    compression_level TINYINT UNSIGNED NOT NULL COMMENT '本轮压缩等级',
    user_token_estimate INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户输入估算 Token',
    assistant_token_estimate INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '助手回答估算 Token',
    final_model_call_id BIGINT UNSIGNED NULL COMMENT '最终成功主模型调用主键',
    error_code VARCHAR(64) NULL COMMENT '脱敏错误码',
    error_message VARCHAR(1024) NULL COMMENT '脱敏错误摘要',
    finish_time DATETIME(3) NULL COMMENT '终态时间',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_conversation_turn_no (conversation_id, turn_no),
    UNIQUE KEY uk_task_id (task_id(128)),
    KEY idx_conversation_status_turn (conversation_id, status, turn_no),
    KEY idx_status_update_time (status, update_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '会话轮次';

CREATE TABLE IF NOT EXISTS turn_tool_call (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    turn_id BIGINT UNSIGNED NOT NULL COMMENT '所属轮次主键',
    agent_step_no INT UNSIGNED NOT NULL COMMENT '轮次内 Agent 推理步骤',
    call_no INT UNSIGNED NOT NULL COMMENT '当前步骤内调用顺序',
    call_id VARCHAR(128) NOT NULL COMMENT '模型工具调用标识',
    tool_name VARCHAR(128) NOT NULL COMMENT '工具名称',
    arguments_content TEXT NOT NULL COMMENT '脱敏后的原始参数字符串',
    status TINYINT UNSIGNED NOT NULL COMMENT '工具调用状态',
    result_summary TEXT NULL COMMENT '可持久化关键结果摘要',
    result_reference VARCHAR(256) NULL COMMENT '受控结果引用或链路标识',
    error_code VARCHAR(64) NULL COMMENT '工具错误码',
    error_message VARCHAR(1024) NULL COMMENT '脱敏错误摘要',
    latency_millis BIGINT UNSIGNED NULL COMMENT '调用耗时毫秒数',
    start_time DATETIME(3) NULL COMMENT '开始时间',
    finish_time DATETIME(3) NULL COMMENT '结束时间',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_turn_step_call_no (turn_id, agent_step_no, call_no),
    UNIQUE KEY uk_turn_step_call_id (turn_id, agent_step_no, call_id(128)),
    KEY idx_turn_status (turn_id, status),
    KEY idx_status_update_time (status, update_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '轮次工具调用';

CREATE TABLE IF NOT EXISTS conversation_summary (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    conversation_id BIGINT UNSIGNED NOT NULL COMMENT '所属会话主键',
    summary_version INT UNSIGNED NOT NULL COMMENT '摘要版本',
    previous_summary_id BIGINT UNSIGNED NULL COMMENT '来源摘要主键',
    covered_start_turn_no INT UNSIGNED NOT NULL COMMENT '覆盖起始轮次',
    covered_end_turn_no INT UNSIGNED NOT NULL COMMENT '覆盖结束轮次',
    summary_content MEDIUMTEXT NOT NULL COMMENT '摘要正文',
    summary_token_estimate INT UNSIGNED NOT NULL COMMENT '摘要估算 Token',
    compression_level TINYINT UNSIGNED NOT NULL COMMENT '压缩等级',
    model_call_id BIGINT UNSIGNED NOT NULL COMMENT '压缩模型调用主键',
    provider_code VARCHAR(64) NOT NULL COMMENT '压缩模型供应方编码',
    route_id VARCHAR(64) NOT NULL COMMENT '压缩模型路由标识',
    api_protocol VARCHAR(32) NOT NULL COMMENT '压缩模型协议',
    model_name VARCHAR(128) NOT NULL COMMENT '压缩模型名称',
    prompt_version VARCHAR(64) NOT NULL COMMENT '摘要提示词版本',
    prompt_hash CHAR(64) NOT NULL COMMENT '摘要提示词内容哈希',
    status TINYINT UNSIGNED NOT NULL COMMENT '摘要状态',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_conversation_summary_version (conversation_id, summary_version),
    KEY idx_conversation_covered_end (conversation_id, covered_end_turn_no),
    KEY idx_conversation_status_version (conversation_id, status, summary_version)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '会话摘要';

CREATE TABLE IF NOT EXISTS model_call_record (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    conversation_id BIGINT UNSIGNED NOT NULL COMMENT '所属会话主键',
    turn_id BIGINT UNSIGNED NULL COMMENT '所属轮次主键',
    task_id VARCHAR(128) NOT NULL COMMENT '调用链路标识',
    provider_request_id VARCHAR(128) NULL COMMENT '供应方请求标识',
    call_type TINYINT UNSIGNED NOT NULL COMMENT '模型调用用途',
    agent_step_no INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '轮次内主模型调用序号，压缩调用固定为0',
    attempt_no INT UNSIGNED NOT NULL COMMENT '同一步骤调用尝试序号',
    status TINYINT UNSIGNED NOT NULL COMMENT '模型调用状态',
    apply_status TINYINT UNSIGNED NOT NULL COMMENT '派生结果应用状态',
    provider_code VARCHAR(64) NOT NULL COMMENT '模型供应方编码',
    route_id VARCHAR(64) NOT NULL COMMENT '模型路由标识',
    api_protocol VARCHAR(32) NOT NULL COMMENT '模型协议',
    model_name VARCHAR(128) NOT NULL COMMENT '模型名称',
    estimated_input_tokens INT UNSIGNED NOT NULL COMMENT '调用前估算输入 Token',
    input_tokens INT UNSIGNED NULL COMMENT '实际输入 Token',
    output_tokens INT UNSIGNED NULL COMMENT '实际输出 Token',
    reasoning_tokens INT UNSIGNED NULL COMMENT '隐藏推理 Token',
    cached_input_tokens INT UNSIGNED NULL COMMENT '缓存命中输入 Token',
    total_tokens INT UNSIGNED NULL COMMENT '实际总 Token',
    context_window INT UNSIGNED NOT NULL COMMENT '模型上下文窗口',
    max_output_tokens INT UNSIGNED NOT NULL COMMENT '最大输出 Token',
    history_end_turn_no INT UNSIGNED NULL COMMENT '完整回放历史终点',
    compression_end_turn_no INT UNSIGNED NULL COMMENT '压缩计划覆盖终点',
    is_anchor_reusable TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否可作增量估算锚点',
    summary_version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用的摘要版本',
    context_version INT UNSIGNED NOT NULL COMMENT '使用的上下文版本',
    context_fingerprint CHAR(64) NOT NULL COMMENT '可复用上下文前缀指纹',
    system_prompt_version VARCHAR(64) NOT NULL COMMENT '系统提示词版本',
    system_prompt_hash CHAR(64) NOT NULL COMMENT '系统提示词内容哈希',
    tool_definition_version VARCHAR(64) NOT NULL COMMENT '工具定义版本',
    tool_schema_hash CHAR(64) NOT NULL COMMENT '实际工具定义哈希',
    compression_level TINYINT UNSIGNED NOT NULL COMMENT '调用时压缩等级',
    latency_millis BIGINT UNSIGNED NULL COMMENT '调用耗时毫秒数',
    error_code VARCHAR(64) NULL COMMENT '模型错误码',
    error_message VARCHAR(1024) NULL COMMENT '脱敏错误摘要',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_turn_call_attempt (turn_id, call_type, agent_step_no, attempt_no),
    UNIQUE KEY uk_task_call_attempt (task_id(128), call_type, agent_step_no, attempt_no),
    KEY idx_task_call_step (task_id(128), call_type, agent_step_no, id),
    KEY idx_turn_call_step (turn_id, call_type, agent_step_no, id),
    KEY idx_conversation_call_status (conversation_id, call_type, status, id),
    KEY idx_status_update_time (status, update_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '模型调用记录';
